-- 1. Enable the pgvector extension (adds support for vector search)
create extension if not exists vector;

-- 2. Create the memories table
create table if not exists memories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  embedding vector(1536), -- 1536 dimensions matches standard embedding models like text-embedding-3-small
  metadata jsonb
);

-- 3. Create similarity matching function (used via rpc() in Supabase client)
create or replace function match_memories (
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language sql stable
as $$
  select
    memories.id,
    memories.content,
    memories.metadata,
    1 - (memories.embedding <=> query_embedding) as similarity
  from memories
  where 1 - (memories.embedding <=> query_embedding) > match_threshold
  order by memories.embedding <=> query_embedding
  limit match_count;
$$;
