-- SpendWise AI Version 2 Production-Grade Supabase Database Schema

-- 1. Enable vector extension for vector embeddings & similarity search
create extension if not exists vector;

-- 2. Expenses Table (with Idempotency Keys, User Isolation, and Agent Metadata)
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  amount numeric(12, 2) not null,
  category text not null,
  description text not null,
  merchant text,
  paymentmethod text default 'UPI',
  date date not null default CURRENT_DATE,
  notes text,
  source text default 'manual',
  receipt_url text,
  idempotency_key uuid unique,
  created_by_agent boolean default false,
  confidence numeric(3, 2)
);

create index if not exists idx_expenses_user_id on expenses(user_id);
create index if not exists idx_expenses_date on expenses(date desc);
create index if not exists idx_expenses_category on expenses(category);
create index if not exists idx_expenses_idempotency on expenses(idempotency_key);

-- Enable RLS on expenses
alter table expenses enable row level security;

-- Explicit 4-Part RLS Policies for Expenses
create policy "users_select_own_expenses"
on expenses for select
using (auth.uid() = user_id);

create policy "users_insert_own_expenses"
on expenses for insert
with check (auth.uid() = user_id);

create policy "users_update_own_expenses"
on expenses for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users_delete_own_expenses"
on expenses for delete
using (auth.uid() = user_id);


-- 3. Category Budgets Table
create table if not exists budgets (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid(),
  category text not null,
  allocated_amount numeric(12, 2) not null,
  period text default 'monthly',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint unique_user_category unique (user_id, category)
);

alter table budgets enable row level security;

create policy "users_select_own_budgets" on budgets for select using (auth.uid() = user_id);
create policy "users_insert_own_budgets" on budgets for insert with check (auth.uid() = user_id);
create policy "users_update_own_budgets" on budgets for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users_delete_own_budgets" on budgets for delete using (auth.uid() = user_id);


-- 4. Peer Records Table (Lending & Borrowing Ledger)
create table if not exists peer_records (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  amount numeric(12, 2) not null,
  original_amount numeric(12, 2) not null,
  type text not null check (type in ('lent', 'borrowed')),
  description text default 'Split Share',
  date date not null default CURRENT_DATE,
  due_date date,
  status text not null default 'pending' check (status in ('pending', 'settled')),
  payments jsonb default '[]'::jsonb,
  idempotency_key uuid unique
);

alter table peer_records enable row level security;

create policy "users_select_own_peers" on peer_records for select using (auth.uid() = user_id);
create policy "users_insert_own_peers" on peer_records for insert with check (auth.uid() = user_id);
create policy "users_update_own_peers" on peer_records for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users_delete_own_peers" on peer_records for delete using (auth.uid() = user_id);


-- 5. Receipts Table (OCR Metadata & retention policy)
create table if not exists receipts (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid(),
  expense_id bigint references expenses(id) on delete cascade,
  image_url text not null,
  ocr_raw_text text,
  confidence numeric(3, 2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table receipts enable row level security;
create policy "users_own_receipts" on receipts for all using (auth.uid() = user_id);


-- 6. AI Conversations & Messages (Retrieval-Based Chat Memory)
create table if not exists ai_conversations (
  id uuid default gen_random_uuid() primary key,
  user_id uuid default auth.uid(),
  title text default 'AI Finance Session',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists ai_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid references ai_conversations(id) on delete cascade,
  sender text not null check (sender in ('user', 'assistant')),
  text text not null,
  tool_calls jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table ai_conversations enable row level security;
alter table ai_messages enable row level security;

create policy "users_own_conversations" on ai_conversations for all using (auth.uid() = user_id);
create policy "users_own_messages" on ai_messages for all using (
  exists (
    select 1 from ai_conversations c where c.id = ai_messages.conversation_id and c.user_id = auth.uid()
  )
);


-- 7. Sync Events Audit Table (Offline Replay Debugging)
create table if not exists sync_events (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid(),
  action_type text not null,
  idempotency_key uuid not null,
  status text not null check (status in ('replayed', 'duplicate_skipped', 'failed')),
  error_message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table sync_events enable row level security;
create policy "users_own_sync_events" on sync_events for all using (auth.uid() = user_id);
