-- SpendWise AI Complete Supabase Database Schema

-- 1. Enable the pgvector extension (for AI Second Brain vector embeddings)
create extension if not exists vector;

-- 2. Create the Expenses Table
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  amount numeric(12, 2) not null,
  category text not null,
  description text not null,
  merchant text,
  paymentmethod text default 'UPI',
  date date not null default CURRENT_DATE,
  notes text,
  source text default 'manual',
  receipt_url text
);

-- Index for date queries & filtering
create index if not exists idx_expenses_date on expenses(date desc);
create index if not exists idx_expenses_category on expenses(category);

-- 3. Create the Peer Records Table (Lending & Borrowing Ledger)
create table if not exists peer_records (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  amount numeric(12, 2) not null,
  original_amount numeric(12, 2) not null,
  type text not null check (type in ('lent', 'borrowed')),
  description text default 'Split Share',
  date date not null default CURRENT_DATE,
  due_date date,
  status text not null default 'pending' check (status in ('pending', 'settled')),
  payments jsonb default '[]'::jsonb
);

create index if not exists idx_peer_status on peer_records(status);
create index if not exists idx_peer_name on peer_records(name);

-- 4. Create the Memories Table (Second Brain Notes & Income Logs)
create table if not exists memories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  embedding vector(768), -- 768 dimensions for Google Gemini text-embedding-004 model
  metadata jsonb
);

-- 5. Similarity Matching RPC Function for Supabase Vector Search
create or replace function match_memories (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language sql stable
as $$
  select
    memories.id,
    memories.content,
    memories.metadata,
    1 - (memories.embedding <=> query_embedding) as similarity
  from memories
  where 1 - (memories.embedding <=> query_embedding) > match_threshold
  order by memories.embedding <=> query_embedding
  limit match_count;
$$;

